name: Build & Test WebGoat
on: 
    push:
        branches:
            - main

jobs:
    build:
        name: "Build" 
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4

            - name: "Setup Java"
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '23'

            - name: "Build with Maven"
              run: ./mvnw clean install #Construir la aplicación
              
              continue-on-error: false #Si falla, se detiene el pipeline
    test:
        name: "Test"
        runs-on: ubuntu-latest
        needs: build #El job sólo se ejecutará si build fue correctamente ejecutado
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4

            - name: "Setup Java"
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '23'

            - name: "Run Tests with Maven"
              run: ./mvnw test #Para ejecutar las pruebas unitarias

              continue-on-error: false 