name: Test Shared Workflow

on:
  push:
    branches:
      - main

jobs:
  test-shared-workflow:
    uses: ./.github/workflows/pipeline-actions.yml
    with:
      java-v: '23'
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}